### ISSUE TITLE
El perfil del Admin esta incompleto

### ISSUE THREAD

**Issue by Mudufin-184** [JuanDavidZabalaTapiero/Proyecto-loviingStore#3]
Quitar los botones del header, configuración y cambiar unas cosas del perfil

**Comment by JuanDavidZabalaTapiero** [comment]
Hola Jean Carlos

**Comment by JuanDavidZabalaTapiero** [comment]
Ya arreglo eso :D 👍

**Comment by Mudufin-184** [comment]
Listo quedo atento 
![Capibara](https://github.com/user-attachments/assets/0e01a9a9-1b56-42bf-ba1e-3e604376cd3e)

**Comment by JuanDavidZabalaTapiero** [comment]
Listo ya quedo el perfil

**Comment by Mudufin-184** [comment]
![descarga](https://github.com/user-attachments/assets/88ec58a5-74f8-4957-94e8-383e2a07df7f)
epa
